const productos = [
    // Productos de Jeans
    {
      id: 1,
      nombre: 'Jeans ajustados de mezclilla oscura',
      categoria: 'Jeans',
      precio: 49.99,
      descripcion: 'Jeans ajustados con un tono de mezclilla oscuro para un look elegante.',
      quantity: 3,
      imagen: '/jean01.jpg',
    },
    {
      id: 2,
      nombre: 'Jeans desgastados estilo vintage',
      categoria: 'Jeans',
      precio: 59.99,
      descripcion: 'Jeans con un toque desgastado y estilo vintage para un look casual.',
      imagen:  '/jean02.jpg',
      quantity: 3,
    },
    {
      id: 3,
      nombre: 'Jeans de pierna recta clásicos',
      categoria: 'Jeans',
      precio: 44.99,
      descripcion: 'Jeans de pierna recta, clásicos y versátiles para cualquier ocasión.',
      imagen:  '/jean03.jpg',
      quantity: 3,
    },
    {
      id: 4,
      nombre: 'Jeans con roturas y rasgaduras',
      categoria: 'Jeans',
      precio: 54.99,
      descripcion: 'Jeans modernos con roturas y rasgaduras para un look atrevido y a la moda.',
      imagen:  '/jean04.jpg',
      quantity: 3,
    },
    {
      id: 5,
      nombre: 'Jeans de corte slim con lavado claro',
      categoria: 'Jeans',
      precio: 47.99,
      descripcion: 'Jeans de corte slim con un lavado claro para un estilo fresco y moderno.',
      imagen:  '/jean05.jpg',
      quantity: 3,
    },
    {
      id: 6,
      nombre: 'Jeans elásticos para mayor comodidad',
      categoria: 'Jeans',
      precio: 49.99,
      descripcion: 'Jeans con tejido elástico para una mayor comodidad durante todo el día.',
      imagen:  '/jean06.jpg',
      quantity: 3,
    },
    {
      id: 7,
      nombre: 'Jeans de estilo boyfriend',
      categoria: 'Jeans',
      precio: 52.99,
      descripcion: 'Jeans de estilo boyfriend para un look relajado y casual.',
      imagen:  '/jean07.jpg',
      quantity: 3,
    },
  
    // Productos de Polos
    {
      id: 8,
      nombre: 'Polo de algodón básico',
      categoria: 'Polos',
      precio: 29.99,
      descripcion: 'Polo clásico de algodón para un estilo cómodo y casual.',
      imagen: '/polo01.jpg',
      quantity: 3,
    },
    {
      id: 9,
      nombre: 'Polo de rayas elegante',
      categoria: 'Polos',
      precio: 34.99,
      descripcion: 'Polo con diseño de rayas para un toque elegante.',
      imagen: '/polo02.webp',
      quantity: 3,
    },
    {
      id: 10,
      nombre: 'Polo deportivo transpirable',
      categoria: 'Polos',
      precio: 39.99,
      descripcion: 'Polo deportivo con tejido transpirable para actividades activas.',
      imagen: '/polo03.webp',
      quantity: 3,
    },
    {
      id: 11,
      nombre: 'Polo de manga larga',
      categoria: 'Polos',
      precio: 32.99,
      descripcion: 'Polo con manga larga para un estilo versátil.',
      imagen: '/polo04.webp',
      quantity: 3,
    },
    {
      id: 12,
      nombre: 'Polo con logotipo bordado',
      categoria: 'Polos',
      precio: 37.99,
      descripcion: 'Polo con logotipo bordado para un toque distintivo.',
      imagen: '/polo05.jpg',
      quantity: 3,
    },
  
    // Productos de Camisas
    {
      id: 13,
      nombre: 'Camisa de lino casual',
      categoria: 'Camisas',
      precio: 44.99,
      descripcion: 'Camisa de lino ligera y casual para días cálidos.',
      imagen: '/camisa01.jpg',
      quantity: 3,
    },
    {
      id: 14,
      nombre: 'Camisa a cuadros clásica',
      categoria: 'Camisas',
      precio: 49.99,
      descripcion: 'Camisa a cuadros clásica para un estilo atemporal.',
      imagen: '/camisa02.jpg',
      quantity: 3,
    },
    {
      id: 15,
      nombre: 'Camisa de vestir elegante',
      categoria: 'Camisas',
      precio: 54.99,
      descripcion: 'Camisa de vestir elegante para ocasiones formales.',
      imagen: '/camisa03.jpg',
      quantity: 3,
    },
    {
      id: 16,
      nombre: 'Camisa de denim moderna',
      categoria: 'Camisas',
      precio: 39.99,
      descripcion: 'Camisa de denim moderna para un look informal y a la moda.',
      imagen: '/camisa04.webp',
      quantity: 3,
    },
    {
      id: 17,
      nombre: 'Camisa estampada con motivos florales',
      categoria: 'Camisas',
      precio: 47.99,
      descripcion: 'Camisa con estampado floral para un toque fresco y primaveral.',
      imagen: '/camisa05.webp',
      quantity: 3,
    },
    {
      id: 18,
      nombre: 'Camisa de manga corta con bolsillo',
      categoria: 'Camisas',
      precio: 42.99,
      descripcion: 'Camisa de manga corta con un práctico bolsillo en el pecho.',
      imagen: '/camisa06.jpg',
      quantity: 3,
    },
    {
      id: 19,
      nombre: 'Camisa vaquera con botones',
      categoria: 'Camisas',
      precio: 49.99,
      descripcion: 'Camisa vaquera con cierre de botones para un look casual.',
      imagen: '/camisa07.jpg',
      quantity: 3,
    },
  ];


  export {
     productos, 
  }